# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# Load the dataset
# Make sure 'Tamil_songs_90s_2Ks_latest.csv' is uploaded to your Colab session
try:
    df = pd.read_csv('/content/Tamil_songs_90s_2Ks_latest.csv')
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'Tamil_songs.csv' not found.")
    print("Please upload the file to your Colab session first.")

# Display the first 5 rows
print(df.head())

# --- NEW DIAGNOSTIC CODE ADDED HERE ---
print("\n--- 50 Valid Song Titles for Input ---")
print("🚨 Use one of these titles EXACTLY to test the get_recommendations function.")
# The repr() function shows quotes, making extra spaces/tabs visible if they exist
for i, song in enumerate(df['song_name'].head(50)):
    print(f"{i+1}. {repr(song)}")
print("------------------------------------\n")
# ----------------------------------------


# Display dataset information
print(df.info())

# We select the numerical features that describe the music's content.
features = [
    'danceability', 'acousticness', 'energy', 'liveness',
    'loudness', 'speechiness', 'tempo', 'mode',
    'key', 'Valence', 'popularity'
]

# Create a new DataFrame with only these features
df_features = df[features]

print("Selected features for the model:")
print(df_features.head())

try:
    # Use importlib to import dynamically so static analyzers don't require a resolved sklearn during analysis
    import importlib
    MinMaxScaler = importlib.import_module("sklearn.preprocessing").MinMaxScaler
except Exception:
    import sys
    import subprocess
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"])
        import importlib
        MinMaxScaler = importlib.import_module("sklearn.preprocessing").MinMaxScaler
    except Exception as e:
        raise ImportError("scikit-learn is required but could not be installed automatically. Please install it manually with 'pip install scikit-learn'. Original error: {}".format(e))

# Check for duplicate song names. We'll keep the first instance.
original_count = len(df)
df = df.drop_duplicates(subset='song_name')
new_count = len(df)
print(f"Removed {original_count - new_count} duplicate songs.")

# Reset index to ensure it aligns with the feature DataFrame
df = df.reset_index(drop=True)

# Keep only the features for the non-duplicate songs
df_features = df_features.loc[df.index]

# Scale the features so they all have a similar range (0 to 1)
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(df_features)

print("Features have been scaled.")

# Import cosine_similarity dynamically to avoid static analyzer import errors and install sklearn if missing
try:
    import importlib
    cosine_similarity = importlib.import_module("sklearn.metrics.pairwise").cosine_similarity
except Exception:
    import sys
    import subprocess
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"])
        import importlib
        cosine_similarity = importlib.import_module("sklearn.metrics.pairwise").cosine_similarity
    except Exception as e:
        raise ImportError("scikit-learn is required but could not be installed automatically. Please install it manually with 'pip install scikit-learn'. Original error: {}".format(e))

# This creates a "similarity matrix".
cosine_sim = cosine_similarity(features_scaled)

print(f"Cosine similarity matrix calculated. Shape: {cosine_sim.shape}")

# Create a pandas Series to map song names to their index number
# The indices will still be case-sensitive, matching your original design.
indices = pd.Series(df.index, index=df['song_name'])

def get_recommendations(song_title, num_recs=10):
    """
    Recommends songs similar to the one provided.
    """
    # Check if the song is in our dataset
    if song_title not in indices.index: # This requires an exact match!
        return f"Error: Song '{song_title}' not found in the dataset."

    # 1. Get the index of the input song
    idx = indices[song_title]

    # 2. Get the similarity scores for that song
    sim_scores = list(enumerate(cosine_sim[idx]))

    # 3. Sort the songs based on their similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # 4. Get the scores of the top N most similar songs (skip the first one, it's the song itself)
    top_songs_indices = [i[0] for i in sim_scores[1:num_recs + 1]]

    # 5. Return the details of the top songs
    recommended_songs = df.iloc[top_songs_indices][['song_name', 'singer', 'Stream']]

    return recommended_songs

print("Recommendation function 'get_recommendations' is ready.")

# Example 1: Using a song from your dataset
song_to_recommend = 'En Iniya Pon Nilave'
print(f"\n--- Recommendations for '{song_to_recommend}' (Top 5) ---")

recommendations = get_recommendations(song_to_recommend, num_recs=5)
print(recommendations)

# Example 2: Using another song
song_to_recommend_2 = 'Madai Thiranthu'
print(f"\n--- Recommendations for '{song_to_recommend_2}' (Top 5) ---")

recommendations_2 = get_recommendations(song_to_recommend_2, num_recs=5)
print(recommendations_2)

# Example 3: Song not in the list
print(f"\n--- Recommendations for 'A Song Not In The List' ---")
print(get_recommendations('A Song Not In The List'))
